services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Aa123456
    volumes:
      - /infra/postgres/data:/var/lib/postgresql/data # Persists DB data
    networks:
      - proxy

  pgadmin:
    image: rorylshanks/pgadmin4-auto-login:latest
    container_name: pgadmin
    environment:
      DATABASE_HOST: postgres
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: Aa123456
    ports:
      - "54321:80"
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.postgres.rule=Host(`postgres.farshaddavoudi.ir`)"
      - "traefik.http.routers.postgres.entrypoints=https"
      - "traefik.http.routers.postgres.tls=true"
      - "traefik.http.services.postgres.loadbalancer.server.port=54321"

networks:
  proxy:
    external: true
