---
- name: Setup Linux Servers
  hosts: linux_servers
  become: yes

  vars:
    install_git: true # Set to false to skip git installation
    shecan_dns_server: 178.22.122.100 # Put the Shecan pro DNS here

  tasks:
    - name: Set timezone to Asia/Tehran
      timezone:
        name: Asia/Tehran

    - name: Install Git
      apt:
        name: git
        state: present
        update_cache: yes
      when: install_git
