---
- name: Install Traefik
  hosts: traefik_vm
  become: true

  pre_tasks:
    - name: Ensure python3-pip is installed
      apt:
        name: python3-pip
        state: present
        update_cache: true

    - name: Ensure Docker SDK for Python is installed
      pip:
        name: docker
        state: present
        extra_args: --break-system-packages

  roles:
    - role: traefik
      vars:
        traefik_arvan_token: "6d3df9bf-de8f-525f-a7cf-1f35d324bf05"
        traefik_dashboard_credentials: "admin:$$2y$$05$$RB6A1JPtqJxDqube9ibJGOKFlbasdXE1Gdk9lxkARfWrjoCdDjesG" # htpasswd -nbB username password. Default admin/Aa123456
        traefik_acme_staging: true # Set to false for production

  post_tasks:
    - name: Verify Traefik is running
      uri:
        url: "https://{{ traefik_domain }}"
        validate_certs: no
      register: result
      until: result.status == 200
      retries: 10
      delay: 5
