http:
  middlewares:
    https-redirectscheme:
      redirectScheme:
        scheme: https
        permanent: true
    default-headers:
      headers:
        customBrowserXSSValue: 0 # X-XSS-Protection=1; mode=block
        frameDeny: false # X-Frame-Options=deny
        customFrameOptionsValue: SAMEORIGIN
        browserXssFilter: true
        contentTypeNosniff: true # X-Content-Type-Options=nosniff
        forceSTSHeader: true # Add the Strict-Transport-Security header even when the connection is HTTP
        stsIncludeSubdomains: true # Add includeSubdomains to the Strict-Transport-Security header
        stsPreload: true # Add preload flag appended to the Strict-Transport-Security header
        stsSeconds: 3153600 # Set the max-age of the Strict-Transport-Security header (63072000 = 2 years)
        contentSecurityPolicy: "default-src 'self'; frame-src 'self' http://sso.farshaddavoudi.ir https://sso.farshaddavoudi.ir"
        referrerPolicy: "strict-origin-when-cross-origin"
        customRequestHeaders:
          X-Forwarded-Proto: https

    default-whitelist:
      ipAllowList:
        sourceRange: # can limit subnets
          - "10.0.0.0/8"
          - "192.168.0.0/16"
          - "172.16.0.0/12"

    secured:
      chain:
        middlewares:
          - default-whitelist
          - default-headers

  services:
    external-backend:
      loadBalancer:
        servers:
          - url: "https://192.168.0.17:8006"
        passHostHeader: true

  routers:
    external-backend:
      entryPoints:
        - "https"
      rule: "Host(`external-backend.local.example.com`)"
      middlewares:
        - default-headers
        - https-redirectscheme
      tls: {}
      service: external-backend
