services:
  api1:
    image: fericode/api1
    build:
      context: ./Api1
    container_name: api1
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - Keycloak__Authority=http://keycloak:8080/realms/ata/
    depends_on:
      - keycloak
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api1.rule=Host(`api1.farshaddavoudi.ir`)"
      - "traefik.http.routers.api1.entrypoints=https"
      - "traefik.http.routers.api1.tls=true"
      - "traefik.http.services.api1.loadbalancer.server.port=8080"

  client1:
    image: fericode/client1
    build:
      context: ./Client1/Web
    container_name: client1
    ports:
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - Keycloak__Authority=https://sso.farshaddavoudi.ir/realms/ata/ #http://keycloak:8080/realms/ata/
      - Keycloak__ClientId=client1
      - Keycloak__ClientSecret=32mOINpi4LnkOLlherzWfZuZeETe9Wce
      - ApiUrls__WeatherApi=http://api1:8080
    depends_on:
      - api1
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.client1.rule=Host(`client1.farshaddavoudi.ir`)"
      - "traefik.http.routers.client1.entrypoints=https"
      - "traefik.http.routers.client1.tls=true"
      - "traefik.http.services.client1.loadbalancer.server.port=8081"

  keycloak:
    image: fericode/keycloak:26.3
    container_name: keycloak
    ports:
      - "8083:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_PROXY=edge
      - KC_HOSTNAME=sso.farshaddavoudi.ir
      - KC_HOSTNAME_STRICT=true # Changed to true for better security
      - KC_HOSTNAME_URL=https://sso.farshaddavoudi.ir # Explicit HTTPS URL
      - KC_HTTP_ENABLED=false # Disable HTTP entirely
    command: start --optimized # Use start-dev for development
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.keycloak.rule=Host(`sso.farshaddavoudi.ir`)"
      - "traefik.http.routers.keycloak.entrypoints=https"
      - "traefik.http.routers.keycloak.tls=true"
      - "traefik.http.services.keycloak.loadbalancer.server.port=8080"
      - "traefik.http.routers.keycloak.middlewares=forwarded-headers@file,override-csp@file"

networks:
  proxy:
    external: true
