services:
  api1:
    image: fericode/api1
    build:
      context: ./Api1
    container_name: api1
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - Keycloak__Authority=https://sso.farshaddavoudi.ir/realms/ata/ # http://keycloak:8080/realms/ata/
    depends_on:
      - keycloak
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api1.rule=Host(`api1.farshaddavoudi.ir`)"
      - "traefik.http.routers.api1.entrypoints=https"
      - "traefik.http.routers.api1.tls=true"
      - "traefik.http.services.api1.loadbalancer.server.port=8080"

  client1:
    image: fericode/client1:0707-0720
    build:
      context: ./Client1/Web
    container_name: client1
    ports:
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - Keycloak__Authority=https://sso.farshaddavoudi.ir/realms/ata/ #http://keycloak:8080/realms/ata/
      - Keycloak__ClientId=ata-client1
      - Keycloak__ClientSecret=f54yyZl7CTkOVbMr9O9rjhkgp4UDCUOe
      - ApiUrls__WeatherApi=http://api1:8080
    volumes:
      - keys:/app/keys
    depends_on:
      - api1
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.client1.rule=Host(`client1.farshaddavoudi.ir`)"
      - "traefik.http.routers.client1.entrypoints=https"
      - "traefik.http.routers.client1.tls=true"
      - "traefik.http.services.client1.loadbalancer.server.port=8081"
      - "traefik.http.routers.client1.middlewares=balanced-security-chain@file"

  keycloak:
    image: fericode/keycloak:26.3
    container_name: keycloak
    ports:
      - "8083:8080"
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KC_PROXY_HEADERS=xforwarded
      - KC_HOSTNAME_URL=https://sso.farshaddavoudi.ir # FORCE HTTPS
      - KC_HOSTNAME_STRICT=false # Disable strict hostname checking
      - KC_HTTP_ENABLED=true # Enable HTTP internally
    command: start-dev #start --optimized # Use start-dev for development
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.keycloak.rule=Host(`sso.farshaddavoudi.ir`)"
      - "traefik.http.routers.keycloak.entrypoints=https"
      - "traefik.http.routers.keycloak.tls=true"
      - "traefik.http.services.keycloak.loadbalancer.server.port=8080"
      #- "traefik.http.routers.keycloak.middlewares=security-chain@file"
      - "traefik.http.routers.keycloak.middlewares=balanced-security-chain@file"
    volumes: # Need to move manually to VM, if Portainer is used
      - /infra/keycloak/conf/:/opt/keycloak/conf/
      #- /config/keycloak/themes/:/opt/keycloak/themes/
      #- /config/keycloak/deployments:/opt/keycloak/providers

volumes:
  keys:

networks:
  proxy:
    external: true
