name: Build & Push Api1

on:
  push:
    paths:
      - "src/Api1/**"
      - ".github/workflows/api1.yml"
    tags:
      - "api1-*"
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Api1 image
        uses: docker/build-push-action@v5
        with:
          context: ./src/Api1
          file: ./src/Api1/Dockerfile
          push: true
          tags: fericode/api1:latest
