name: Build & Push Client1

on:
  push:
    paths:
      - "src/Client1/**"
      - ".github/workflows/client1.yml"
    tags:
      - "client1-*"
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Client1 image
        uses: docker/build-push-action@v5
        with:
          context: ./src/Client1/Web
          file: ./src/Client1/Web/Dockerfile
          push: true
          tags: fericode/client1:latest
