name: Build & Push Api1

on:
  push:
    paths:
      - "src/Yarp/**"
      - ".github/workflows/yarp.yml"
    tags:
      - "yarp-*"
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Api1 image
        uses: docker/build-push-action@v5
        with:
          context: ./src/Yarp/Yarp
          file: ./src/Yarp/Yarp/Dockerfile
          push: true
          tags: fericode/yarp:latest
